---
- name: Create initial host groups for localhost
  hosts: localhost
  connection: local
  become: no
  gather_facts: no
  tags:
  - always
  tasks:
  - include_vars: cluster_hosts.yml

- name: Gather nodes hostnames
  setup:
    gather_subset: '!all'
    filter: ansible_*

- name: Assign inventory name to unconfigured hostnames (non-CoreOS)
  hostname:
    name: "{{ ansible_default_ipv4.address|regex_replace('\\.','-')}}"

- name: Assign inventory name to unconfigured hostnames (CoreOS only)
  command: "hostnamectl set-hostname  {{inventory_hostname}}"
  register: hostname_changed

- name: Update hostname fact (CoreOS only)
  setup:
    gather_subset: '!all'
    filter: ansible_hostname